TOP_DIR = ../../..
MODULE_TOP_DIR = .
BUILD_NAME = libhttp_detect
SUB_MOD =
SUB_DIR = 
BUILD_TYPE = dynlib
CFLAGS_LOCAL = -Wno-sign-compare -I../include -I../decode

include $(TOP_DIR)/script/compile.mk
