#!/bin/sh

if [ ${#1} -gt 0 ] && [ ${#2} -gt 0 ] && [ ${#3} -gt 0 ];
then
	file=$3
	bak_file=".$3"
	cp $file .$file
	sed s/$1/$2/g < $bak_file > $file
	rm $bak_file
else
	echo "freplace @target @replace @file"
fi
